FROM python:3.11-slim

WORKDIR /app

COPY requerments.txt .
RUN pip install --no-cache-dir -r requerments.txt

COPY . .

EXPOSE 8081

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081"]